site_name: PhysAI
repo_url: https://github.com/neurdylab/physai
repo_name: neurdylab/physai

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.annotate
    - content.tabs.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: indigo
      accent: indigo

nav:
  - Home: 
    - About: index.md
    - Funding: home/funding.md
    - Contact: home/contact.md
  - Projects: 
    - projects/projects.md
    - projects/deepphysiorecon.md
    - projects/qa.md
  - Resources: 
    - Tutorials: resources/tutorials.md
    - Datasets: resources/datasets.md
  - Publications: 
    - 2024: publications/y4.md
    - 2023: publications/y3.md
    - 2022: publications/y2.md
    - 2021: publications/y1.md
    - 2020: publications/y0.md
  - Collaborations: collaborations.md
  - Team: team.md
  

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://www.github.com/neurdylab
    - icon: fontawesome/brands/twitter
      link: https://www.x.com/neurdylab
    - icon: fontawesome/solid/globe
      link: https://www.cchanglab.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright © 2024 NEURDY Lab