site_name: PhysAI
repo_url: https://github.com/neurdylab/physai
repo_name: neurdylab/physai

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tabs.annotate
    - content.tabs.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: indigo
      accent: indigo
  icon:
    annotation: material/chevron-right-circle

nav:
  - Home: 
    - index.md
    - home/funding.md
    - home/contact.md
  - Projects: 
    - projects/index.md
    - projects/deepphysiorecon.md
    - projects/qa.md
  - Resources: 
    - resources/index.md
    - resources/talks.md
    - resources/tutorials.md
    - resources/datasets.md
  - Publications: 
    - publications/2024.md
    - publications/2023.md
    - publications/2022.md
    - publications/2021.md
    - publications/2020.md
  - Collaborations: collaborations.md
  - Team: team.md
  

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://www.github.com/neurdylab
    - icon: fontawesome/brands/twitter
      link: https://www.x.com/neurdylab
    - icon: fontawesome/solid/globe
      link: https://www.cchanglab.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright © 2024 NEURDY Lab